### PR TITLE
Correct my syntax error from before

### PR DESCRIPTION
**Pull request by richard67**
Correct my syntax error from before: Closing bracket for setQuery call missing.

Sorry, George.

### CODE REVIEW

**Comment by wilsonge** [comment]
Ty!

**Comment by richard67** [comment]
Welcome .. was my mistake anyway, sorry. Tested what we have here now also for my soon coming new PR for the schema manager db fix. Was ok there, i.e. check if conversion already done or not works now here and there.

**Comment by wilsonge** [comment]
Awesome - I've just sat down at my desktop to generate the packages :) So hopefully we'll have this merged soon

**Comment by richard67** [comment]
@wilsonge Would be nice ... and my new PR #9312 ... would be nice if it could be merged soon before next beta or RC.

**Pull request merged**
