### PR TITLE
lower case for integer

### PR DESCRIPTION
**Pull request by alikon**
fix for comment https://github.com/joomla/joomla-cms/pull/28609#issuecomment-612573103

cc @richard67

### CODE REVIEW

**Comment by richard67** [comment]
@alikon The change makes it work, but it would be a bit inconsistent to do the strtolower only at this one place. Currently people just have to use lowercase in the update sql. It is same shit as with "VARCHAR" being used in the installation SQL scripts (formerly joomla.sql) but in update SQL we have to use "character vayring". If we make it case-insensitive, we should to if for all kinds of statements in the schema checker for postgresql.

For now I would say let's just correct it in the update sql script.

**Comment by alikon** [comment]
make sense 
thanks

**Comment by richard67** [comment]
@wilsonge Approved by me.

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
