### PR TITLE
Check saved conversion status

### PR DESCRIPTION
**Pull request by richard67**
Check saved conversion status from DB and execute only if not equal to required status

Please George check if OK.

I am not sure if we need the exception handling for the select statement or if it fits your needs, i.e. return ok or better not, type of message and so on.

I have not tested it yet.

### CODE REVIEW

**Comment by wilsonge** [comment]
I think the exception handling is ok - BUT I think we want a new string to tell users to check the database fixer - rather than displaying the contents of the db error they will likely not understand!

**Comment by wilsonge** [comment]
No wait why are we calling `execute` and `loadResult`? surely we just call `loadResult` in the try and we should be fine?

**Comment by richard67** [comment]
execute? my mistake, was copied from somwehere. yes, move the "$convertedDB = $db->loadResult();" from below to withint the try, replacing the execute thing.

**Comment by wilsonge** [comment]
Awesome :) OK so if you do that. I'll deal with the language string :)

**Comment by richard67** [comment]
Can you check the question in the comment of my last commit?

**Comment by richard67** [comment]
if not visible, i have to initialize it with -1, not with 0, otherwise it will be checked to be ok when equal to uninitilalized value or 0.

**Comment by wilsonge** [comment]
It's visible - obviously if you had gone into the catch it wouldn't be - but as we return there it's not a problem

**Comment by richard67** [comment]
I asked because in c++ it would not be visible outside the try if defined inside it

**Comment by wilsonge** [comment]
well as i'm about to be doing a crap load of c++ debugging for my job next week that's useful to know :P

**Comment by richard67** [comment]
@wilsonge sorry, found syntax error in my select ... closing bracket missing. will make pr for you.

**Pull request merged**
