### PR TITLE
add language filter

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes

added language filter

### Testing Instructions

`JROOT_URL/api/index.php/v1/content/article?filter[language]=de-DE`

### Expected result

filter by language

### CODE REVIEW

**Comment by wilsonge** [comment]
So I'd deliberately left this one out because it's not the primary attribute of the Resource and I wasn't sure if it should be (i.e. we should filter on the content type primary key as opposed to language code)

**Comment by alikon** [comment]
i was testing on a multiligual so i've thinked at it like a missed option.... but yeah let's focus on porting filter on all the core component before

**Comment by wilsonge** [comment]
It's definitely missing and needs to be there before stable. but probably needs a proper discussion

**Comment by alikon** [comment]
ok i'll do a new pr

**Comment by wilsonge** [comment]
thankyou :)

**Pull request closed without merging**
